### ISSUE TITLE
Chapter 15 - Smart Pointers

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#11]

**Comment by hsribei** [comment]
Opa, posso pegar esse?

**Comment by andre-vm** [comment]
Sim! Manda ver! :)

**Comment by hsribei** [comment]
É nóis!

**Comment by hsribei** [comment]
Traduzido: `ch15-00-smart-pointers.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-01-box.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-02-deref.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-03-drop.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-04-rc.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-05-interior-mutability.md`

**Comment by hsribei** [comment]
Traduzido: `ch15-06-reference-cycles.md`

E fim! \o/ Vou dar uma revisada geral no capítulo todo e logo logo envio o PR.
