### ISSUE TITLE
Chapter 13 - Functional Programming features: Closures and Iterators

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#13]

**Comment by rafaelassumpcao** [comment]
gostaria de contribuir com a tradução deste cap, seria possivel?

**Comment by andre-vm** [comment]
É seu, @rafaelassumpcao ! Manda ver!

**Comment by rafaelassumpcao** [comment]
Obrigado @Milack27 , já iniciei aqui... pretendo terminar até o fim de semana que vem, se a semana permitir hehe

**Comment by leoyvens** [comment]
Como está indo @rafaelassumpcao? Precisa de alguma ajuda?

**Comment by marioidival** [comment]
@rafaelassumpcao ping

**Comment by rafaelassumpcao** [comment]
Opa galera, desculpe estive internado por um bom tempo e acabei não dando continuidade. E nesse momento estou com filho pequeno aqui consumindo muito tempo. Se alguém puder dar continuidade na tradução ficaria grato. Vou até ver o que já havia feito e pode ser útil pra galera.

**Comment by marioidival** [comment]
@rafaelassumpcao ok, obrigado !

**Comment by Xunjin** [comment]
Olá traduzi a parte 00 do capítulo 13 e gostaria de um feedback segue link do commit no fork que fiz:
https://github.com/Xunjin/rust-book-pt-br/commit/7d883d4ffc4926033ecc5eec21078425d5c3e705

Tenho algumas dúvidas... Como poderia traduzir Closures e Iterators (Clausuras e Iteradores) ?! Se sim ou não, é possível/plausível colocar algum link ou referência que explique com mais detalhes ?!

**Comment by amargarido** [comment]
Aguardando verificação do Pull Request

**Comment by amargarido** [comment]
@leoyvens , acredito que já possa encerrar essa aqui.
