### ISSUE TITLE
Chapter 10 - Generics

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#16]

**Comment by marimeireles** [comment]
Gostaria de traduzir esse capítulo.

**Comment by marioidival** [comment]
é seu @marimeireles 😬

**Comment by marimeireles** [comment]
@marioidival demorou :)

**Comment by leoyvens** [comment]
@marimeireles Como anda o progresso? Precisa de alguma ajuda?

**Comment by marimeireles** [comment]
@leodasvacas tá indo!
algumas partes tive umas dúvidas, mas, tô deixando pra revisar no final
devo conseguir terminar nessa próxima semana.

**Comment by hsribei** [comment]
Apareceu o termo "generics" pra mim pela primeira vez no capítulo 15.

Depois da primeira ocorrência você está usando em português ou inglês?

**Comment by marimeireles** [comment]
Então, tendo em mente as últimas discussões, acho melhor deixar como generics. 
Uma tradução que pensei foi generalismos, que acho meio estranho.
Por vezes acho que pode ser traduzido como tipos genéricos, se for necessário. Acho que a tradução cabe em alguns contextos.
Mas, como disse, acho que as pessoas vão acabar optando por não traduzir esses termos.

**Comment by leoyvens** [comment]
Acho que "tipos genéricos" é uma tradução bem estabelecida para isto em outras linguagens.

**Comment by marimeireles** [comment]
Sim. 
É que no livro aparecem os termos generics e generic types. Vejo ambos como sinônimos, só fiquei imaginando se existiria algo pra separar os dois, como foi feito no livro. Mas, não pensei em nada bom.
Acho uma boa manter a tradução de tipos genéricos pra ambos os casos.

**Comment by leoyvens** [comment]
Feito em https://github.com/rust-br/rust-book-pt-br/pull/60
