### ISSUE TITLE
Chapter 9 - Error Handling

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#17]

**Comment by amargarido** [comment]
Olá @ericdouglas e @leodasvacas. Gostaria de traduzir esse capítulo.

**Comment by leoyvens** [comment]
Pode mandar ver!

**Comment by Abello966** [comment]
Olá, estou traduzindo o capítulo 09
Terminei a parte 09-00 e 09-01, pretendo fazer o resto em breve

**Comment by amargarido** [comment]
Eu tambem estou. E agora ?

Em 11 de fev de 2018 1:36 PM, "Antonio Augusto Abello" <
notifications@github.com> escreveu:

**Comment by andre-vm** [comment]
Hmm.. isso é um problema. Antes de começar a traduzir um capítulo, é sempre bom verificar se já não tem alguém traduzindo e avisar aqui nas issues, pra evitar esse retrabalho.

@amargarido quais partes do capítulo 9 você já traduziu?

**Comment by leoyvens** [comment]
Eu provoquei a confusão aqui sugerindo o 9 pro @Abello966. O @amargarido topou pegar outro capítulo.

**Comment by andre-vm** [comment]
Ah, beleza. Sendo assim, manda bala, @Abello966 !

**Comment by Abello966** [comment]
Ótimo, terminei o 9.2 hoje, falta só a última parte :)
