### ISSUE TITLE
Chapter 8 - Fundamental Collections

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#18]

**Comment by amargarido** [comment]
@ericdouglas gostaria de ficar com este para traduzir.

**Comment by leoyvens** [comment]
Traduzido!

**Comment by LorhanSohaky** [comment]
Estava fazendo a tradução do capítulo 17, nele é feita uma referência a listagem 8-10, só que, provavelmente, devido a um erro de digitação, no `ch08-01-vectors.md` está escrito "Listagem 8-1"

Nota: Sacanagem, kkkk já estava achando que a tradução do capítulo 8 estava incompleto, devida a quantidade de linhas diferentes.
