### ISSUE TITLE
Chapter 6 - Enums

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#20]

**Comment by andre-vm** [comment]
Comecei a traduzir esse capítulo.

**Comment by andre-vm** [comment]
- [x] Seção 6.0: Enums
- [x] Seção 6.1: Definindo uma Enum
- [x] Seção 6.2: Match
- [x] Seção 6.3: If Let

**Comment by leoyvens** [comment]
@Milack27 Este está pronto ou falta algo?

**Comment by andre-vm** [comment]
@leodasvacas Está pronto.
