### ISSUE TITLE
Chapter 5 - Structs

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#21]

**Comment by jotaerreah** [comment]
Bom dia,
Posso tomar conta deste capitulo.
Irei precisar de ajuda a publicar aqui a minha tradução, mas serei o menos complicado possivel.

**Comment by jotaerreah** [comment]
Continuando, uma duvida.
Sendo Tuga, esta tradução faz-me sentido.
O que vocês acham?
A *struct*, or *structure*, is a custom data type that lets us name and package together multiple related values that make up a meaningful group. 
Um *struct*, ou *estrutura*, é um tipo de dados personalizado que nos permite nomear e criar um conjunto de vários valores relacionados que compõem um grupo de dados.

**Comment by marioidival** [comment]
@jotaerreah faz sentido! =)

**Comment by jotaerreah** [comment]
Boa noite,
Neste capitulo estou com o primeiro ficheiro traduzido e o segundo na pagina 4 de 7.
Como posso carregar isto para aqui para revisão?
Tenho windows 10 e nunca mexi no GIT.
Sejam suaves com a critica...

E obrigado pela ajuda.

**Comment by leoyvens** [comment]
@jotaerreah Você já tentou usar a interface web do github para editar os arquivos? Assim você não precisa mexer no Git. Uma dica boa para git no windows é o github desktop: https://desktop.github.com/. Depois nos diga se alguma destas alternativas funcionou, qualquer dúvida pode perguntar.

Outra coisa, nós temos um grupo no Telegram https://t.me/rustlangbr, seria legal se você entrasse lá para facilitar a comunicação.

**Comment by jotaerreah** [comment]
Boas,
Já traduzi Cap5 as duas primeiras partes.
Usei o Git para Desktop e 'Branchei' conforme as instruções.
Fiz o upload do novo branch, e agora como devo fazer o Pull?
Ou é preferível traduzir primeiro tudo?

**Comment by leoyvens** [comment]
@jotaerreah Você pode fazer um pull request com os arquivos que tenha traduzido inteiramente, mas não precisa ser o capítulo inteiro. Você pode abrir o pull pelo botão no canto superior direito do github desktop ou pela interface web na aba "pull requests" no botão "new pull request".

**Comment by jotaerreah** [comment]
@leodasvacas, fiz um pull usando o botão e fui parar lá atrás do sol posto.
Pelo visto tirei uma rifa no rust-book.
Vou ter que ler a p..rra do manual porque nem sequer percebo como fazer um branch com o git-desktop nesta bo..ta.

**Comment by jotaerreah** [comment]
Boa noite,

Na vossa opinião, o borrow do Rust é usado como eu empresto ou eu peço emprestado?

Exemplo
In the signature for `area`, we use `&self` instead of `rectangle: &Rectangle`
because Rust knows the type of `self` is `Rectangle` due to this method being
inside the `impl Rectangle` context. Note that we still need to use the `&`
before `self`, just like we did in `&Rectangle`. Methods can take ownership of
`self`, borrow `self` immutably as we’ve done here, or borrow `self` mutably,
just like any other parameter.

**Comment by leoyvens** [comment]
Borrow é sempre no sentido de pegar emprestado, como no `&self`.

Quando é no sentido de emprestar você diz que criou uma referência para o valor.

**Comment by jotaerreah** [comment]
Então, acham que esta é a tradução mais correcta? Tinha inicialmente posto ( emprestar `self` imutavel)

In the signature for `area`, we use `&self` instead of `rectangle: &Rectangle`
because Rust knows the type of `self` is `Rectangle` due to this method being
inside the `impl Rectangle` context. Note that we still need to use the `&`
before `self`, just like we did in `&Rectangle`. Methods can take ownership of
`self`, borrow `self` immutably as we’ve done here, or borrow `self` mutably,
just like any other parameter.

Na assinatura de `area`, usamos `&self` em vez de `rectangle: &Rectangle` porque
Rust sabe que o tipo de `self` é `Rectangle` devido a este método estar dentro do 
contexto do `impl Rectangle`. Note que ainda precisamos usar o `&` antes de 
`self`, tal como fizemos em `&Rectangle`. Métodos podem apropriar-se de `self`,
pedir emprestado `self` imutavel como temos feito aqui, ou pedir emprestado `self` 
mutavel, assim como qualquer outro parâmetro.

**Comment by leoyvens** [comment]
Esta ótima a tradução. Acho que o termo mais difícil é _ownership_. Em frases como "ownership é uma característica única de Rust" eu não traduziria. Já em "take ownership" a tradução seria _apropriar-se_ mas isso não evoca o conceito da mesma maneira que "take ownership" claramente evoca "ownership". Sugiro usar _mover_ que é transitivo direto e é semelhante ao inglês _to move_ que o compilador usa nas mensagens de erro. Portanto "Métodos podem mover `self`".

Resumindo, para ownership ou não traduzir ou utilizar o verbo _mover_, o que acha?

**Comment by jotaerreah** [comment]
O meu problema acaba por ser esse. Traduzo para alguém que sabe um pouco de inglês e tem alguma noção de programação, ou traduzo para alguém que tem pouca ou nenhuma noção de programação?
Se for pouca ou nenhuma, a frase tem que ser toda refeita para que o "move _self_" faça um sentido aproximado de "apropriar-se de _self_". Na base, algo fica dono dos dados com o "take ownership", isso consegue-se com o apropriar, "ficar dono de",  o "move", para mim fica mais confuso, porque temos que explicar para onde move e o quê. Acho que no fim é mais fácil manter o original, sem tradução. 
Ajuda a entender os erros do compilador, ainda que se perca o objectivo da tradução que é traduzir tudo o que não é código...
Bom, quase a acabar o capitulo, depois temos que ver como vou fazer o pull, peço a vossa muita paciência. Por vezes bloqueio num problema e primeiro que consiga perceber o que está à minha frente.....

**Comment by leoyvens** [comment]
Certamente para alguém que tem noção de programação, com diz a introdução:

"This book is written for a reader who already knows how to program in at least one programming language."

Ótimo que você já está finalizando, podemos seguir a discussão quando fazer o pull com sua tradução. Vc tem que setar os campos do "base fork" e "head fork" quando for criar o pull, tem que setar o base para `rust-br/rust-book-pt-br`.

**Comment by jotaerreah** [comment]
Penso que o cinco está acabado.
Depois digam se é preciso mais alguma coisa do meu lado.

**Comment by leoyvens** [comment]
Traduzido!

**Comment by hsribei** [comment]
Desculpem a ignorância quanto a Rust em si (estou começando a aprender e a traduzir ao mesmo tempo), mas quando se está dando borrow com `&` e o código compila, a coisa está emprestada, certo? Isto é, o "pedido" sempre é concedido, caso em que talvez fosse melhor usar "*pegar* emprestado" como tradução de *borrow* em vez de *pedir* (porque o pedido nunca é negado). O que acham?

**Comment by leoyvens** [comment]
Essa é uma questão interessante, por um lado o compilador usa o verbo _borrow_ e suas conjugações nas mensagens de erro, por outro o livro em si quase nunca usa borrow, ao invés disso fala apenas de _references_, como em "create a reference", "is a reference", etc...

Você tem exemplos de trechos que está traduzindo onde surge esta questão?

**Comment by hsribei** [comment]
Na tradução abaixo usei "**pega** emprestado `self`" em vez de, por exemplo, "**pede** emprestado `self`". Semanticamente está correto?

```
As discussed in Chapter 10, to implement a trait, we need to provide
implementations for the trait’s required methods. The `Deref` trait, provided
by the standard library, requires us to implement one method named `deref` that
borrows `self` and returns a reference to the inner data. Listing 15-10
contains an implementation of `Deref` to add to the definition of `MyBox`:

Conforme discutimos no Capítulo 10, para implementar uma trait, precisamos
prover implementações para os métodos exigidos pela trait. A trait `Deref`,
disponibilizada pela biblioteca padrão, requer que implementemos um método
chamado `deref` que pega emprestado `self` e retorna uma referência para os
dados internos. A listagem 15-10 contém uma implementação de `Deref` que
adiciona à definição de `MeuBox`:
```

**Comment by leoyvens** [comment]
correto!

**Comment by adjoli** [comment]
Prezados,

No arquivo **ch05-00-structs** na versão está disponível , o título não está aparecendo formatado (está aparecendo o # no início do título).
