### ISSUE TITLE
Chapter 4 - Understanding Ownership

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#22]

**Comment by amargarido** [comment]
Alguém traduzindo este ? O histórico acima ficou confuso para mim. Gostaria de pegar este para traduzir.

**Comment by andre-vm** [comment]
Pessoal, pelo que vejo, não tem ninguém trabalhando nesse capítulo por enquanto, então vou começar. Se já tiver alguém empenhado, por favor, manifeste-se! :)

**Comment by andre-vm** [comment]
- [x] 4.0 - Understanding Ownership
- [x] 4.1 - What Is Ownership
- [x] 4.2 - References and Borrowing
- [x] 4.3 - Slices
- [x] Tradução dos diagramas
- [x] Revisão

**Comment by leoyvens** [comment]
Traduzido em #50
