### ISSUE TITLE
Chapter 3 - Common Programming Constructs

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#23]

**Comment by ericdouglas** [comment]
Vou traduzir esse :)

**Comment by jotaerreah** [comment]
Que se passa com este capitulo? Precisam de ajuda?

**Comment by ericdouglas** [comment]
@jotaerreah fique a vontade para iniciar a tradução deste capítulo :+1:

**Comment by jotaerreah** [comment]
Ainda estou a acabar o 5, mas este não tem nada ainda?

**Comment by jotaerreah** [comment]
OK, se este está parado, vou começar.

**Comment by leoyvens** [comment]
@jotaerreah Está trabalhando neste capítulo?

**Comment by disouzaleo** [comment]
@leodasvacas e @jotaerreah posso traduzir esse capítulo ou vocês fizeram alguma coisa ?

**Comment by leoyvens** [comment]
Olá @Lrodlima! Não fiz nada, creio que o @jotaerreah também não, vá em frente!

**Comment by disouzaleo** [comment]
Maravilha já comecei aqui, @leodasvacas

**Comment by LorhanSohaky** [comment]
Comecei a tradução do capítulo 3. Já fiz o ch03-00 e ch03-01. O ch03-02 estou mais ou menos na metade.

**Comment by LorhanSohaky** [comment]
Terminei o ch03-02. Já faço um pull request para adiantar o período de revisão enquanto faço o resto?

**Comment by leoyvens** [comment]
@LorhanSohaky Acho melhor abrir o PR com a tradução completa. De fato estamos sem revisores ultimamente, mas vou tentar revisar quando abrir o PR.

**Comment by LorhanSohaky** [comment]
Tradução concluída!!! Pull request enviado

**Comment by leoyvens** [comment]
Feito em https://github.com/rust-br/rust-book-pt-br/pull/65

**Comment by LorhanSohaky** [comment]
Move para done
