### ISSUE TITLE
Chapter 1 - Introduction

### ISSUE THREAD

**Issue by ericdouglas** [rust-br/rust-book-pt-br#25]

**Comment by andrealmar** [comment]
oi. Pode dar um assign pra mim neste capítulo.

**Comment by marioidival** [comment]
@andrealmar ele é seu ^^. Finalizando ele e mergeando, eu vou conseguir te colocar como colaborador.

**Comment by leoyvens** [comment]
A versão original do capítulo mudou completamente, precisará ser retraduzido.

**Comment by LorhanSohaky** [comment]
Acho que consigo fazer, mas o diretório `second-edition/src` está atualizado? É para fazer a tradução a partir desses arquivos?

**Comment by leoyvens** [comment]
@LorhanSohaky seria bom atualizar antes.

**Comment by LorhanSohaky** [comment]
Alguma dica pra eu não fazer cagada?

**Comment by everton3x** [comment]
Alguém está tá o capítulo 1? Tenho interesse.

**Comment by LorhanSohaky** [comment]
@everton3x , acho que não tem ninguém. Pode mandar bala

**Comment by everton3x** [comment]
Vi que está faltando o ch01-03-hello-cargo. Vou pegar esse por enquanto.

**Comment by everton3x** [comment]
> 
> 
> Vi que está faltando o ch01-03-hello-cargo. Vou pegar esse por enquanto.

Adicionado PR #90

**Comment by adjoli** [comment]
O título original do capítulo 01 é **Getting Started**, o qual acredito que uma tradução melhor seria _Começando_.

Antes desta página é que de fato existe o arquivo ch00-00-introduction.md, o qual observei que não existe tradução para ele ainda. Gostaria de ajudar e poderia começar por este. O que acham?

**Comment by adjoli** [comment]
Tradução em andamento, sendo feita pelo colega Alberto (@amargarido).
