### ISSUE TITLE
Como traduzir Lifetime?

### ISSUE THREAD

**Issue by marimeireles** [rust-br/rust-book-pt-br#45]
Estou traduzindo lifetime como tempo de vida.
Seguindo o que se encontra no [capítulo 6](https://github.com/rust-br/rust-book-pt-br/blob/master/src/ch06-00-enums.md), traduzi o título da mesma forma, mas durante o capítulo estou usando apenas o termo tempo de vida.
Contudo não tenho certeza se é uma boa escolha traduzir lifetime como tempo de vida, visto que é possível que o usuário não ache muito na internet caso busque pelo termo tempo de vida. O que acham?

**Comment by andre-vm** [comment]
Tenho uma ideia que eu acho que você não vai curtir muito: deixar em inglês, rsrs..

Quando o livro está só citando essa característica da linguagem, eu deixaria em inglês. Por exemplo, "add a lifetime annotation to the reference", eu traduziria como "adicionar uma anotação de lifetime à referência". Mas quando o livro se refere ao _conceito_ de lifetime, explicando o que ele significa, acho que tempo de vida, é bem adequado. Talvez dê pra usar a palavra duração, também, dependendo da frase.

**Comment by marimeireles** [comment]
Eu acho que é uma boa! Pelo que eu falei: ser fácil pra pessoa encontrar o termo na internet, caso necessário.
Obrigada pelo feedback.
