### ISSUE TITLE
Configurar o subdomínio livro.rustbr.org para funcionar neste repositório

### ISSUE THREAD

**Issue by barrosgg** [rust-br/rust-book-pt-br#48]
**Tarefa:** Configurar o subdomínio livro.rustbr.org para funcionar no GitHub pages deste repositório.

**Comment by barrosgg** [comment]
Solicitação para criação do subdomínio: https://bugzilla.mozilla.org/show_bug.cgi?id=1437724

**Comment by barrosgg** [comment]
@marioidival, agora é contigo, o livro precisa rodar no GitHub pages.

**Comment by barrosgg** [comment]
@cynthiapereira, o @marioidival fará os ajustes necessários para funcionar o GitHub pages e então você poderá enviar a configuração para o [Terraform](https://github.com/mozilla/partinfra-terraform).

**Comment by marioidival** [comment]
to refs https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by marioidival** [comment]
URL @cynthiapereira @barrosgeraldo 
https://rust-br.github.io/rust-book-pt-br/

**Comment by marioidival** [comment]
resolvido.
