### ISSUE TITLE
Remover arquivos que não tem uso

### ISSUE THREAD

**Issue by leoyvens** [rust-br/rust-book-pt-br#49]
Por exemplo o diretório da first-edition (alguém até traduziu por acidente um capítulo) e o CONTRIBUTING.md em inglês.

**Comment by andre-vm** [comment]
Acho bom, mas talvez traga alguma dificuldade na hora de atualizar o repositório a partir do upstream,

**Comment by leoyvens** [comment]
É um bom ponto, talvez se removermos e adicionarmos no `.gitignore` elas não vão causar problemas durante o merge?

**Comment by andre-vm** [comment]
Talvez eu esteja enganado, mas acho que o .gitignore não vai fazer muita diferença. Ele impede certos arquivos de serem adicionados ao repositório, mas uma vez que o arquivo já está rastreado, o .gitignore não vai deletá-lo. Teríamos que fazer isso manualmente a cada merge.

**Comment by leoyvens** [comment]
É, acho que não vale a pena, deixa quieto.
