### ISSUE TITLE
Como traduzir "to drop"?

### ISSUE THREAD

**Issue by hsribei** [rust-br/rust-book-pt-br#56]
>Variables are dropped in the reverse order of the order in which they were created, so `d` was dropped before `c`.

Estou usando o verbo "desalocar" e suas declinações nos lugares onde o verbo `to drop` ocorre (neste caso, "`d` foi desalocada antes de `c`"), mas suspeito que seja uma tradução ruim.

Não está claro se o verbo "to drop" é usado exclusivamente para se referir à execução do método `drop` quando a trait `Drop` está implementada, caso no qual a desalocação em si viria depois e seria coisa distinta, ou se "to drop" quer dizer a coisa toda (i.e., chamada do método `drop` mais desalocação mais alguma outra coisa que porventura ocorra neste processo de liberação de memória), caso em que "desalocação" seria subconjunto e ainda assim tradução ruim.

O que usar no lugar então? "Destruir" a variável? "Liberar"? "Soltar"? "Dropar"?

**Comment by hsribei** [comment]
>One example is when using smart pointers that manage locks: you might want to force the `drop` method that **releases the lock** to run so other code in the same scope can acquire the lock. Rust doesn’t let us call the `Drop` trait’s `drop` method manually; instead we have to call the `std::mem::drop` function provided by the standard library if we want to force a value to be **dropped** before the end of its scope.

Este exemplo mais a baixo mostra um caso em que "dropped" se refere à execução do `drop`. Neste caso, ela inclui a liberação de um lock, não apenas de uma região de memória, então o verbo tem que ser mais geral que "desalocar".

Estou pendendo para "liberar", mas acho que pode ser ambíguo com o `free` do C/C++ que também se refere apenas a memória, até onde sei.

**Comment by hsribei** [comment]
Estou substituindo por "dropar" por enquanto para ficar fácil encontrar depois e substituir, já que existem outros usos de "desalocar" que são tradução direta do inglês "deallocate".

**Comment by leoyvens** [comment]
Acho que usaria "liberar", mas é uma questão em aberto.

**Comment by hsribei** [comment]
Não sei se conta, mas https://pt.wiktionary.org/wiki/dropar.

**Comment by hsribei** [comment]
Ponto a favor do "destruir": quando se chama `x.drop()` diretamente, o erro diz `explicit use of destructor method; explicit destructor calls not allowed`.

**Comment by hsribei** [comment]
Nevermind:

>This error message states that we’re not allowed to explicitly call `drop`. The error message uses the term *destructor*, which is the general programming term for a function that cleans up an instance. A *destructor* is analogous to a *constructor* that creates an instance. The `drop` function in Rust is ***one particular*** destructor.

**Comment by andre-vm** [comment]
No capítulo 4, eu usei destruir, mesmo. Me pareceu bom:

> Here, s3 goes out of scope and is dropped. s2 goes out of scope but was moved, so nothing happens. s1 goes out of scope and is dropped.

> Aqui, s3 sai de escopo e é destruída. s2 sai de escopo, mas já foi movida, então nada demais acontece. s1 sai de escopo e é destruída.

**Comment by hsribei** [comment]
É, dizer que foi destruída com certeza não é falso, pois o `drop` é *um dos* destruidores possíveis, pelo que parece. Mas o uso do verbo "to drop" parece ser mais específico, querendo dizer "foi destruída *por uma chamada ao método `drop`*.

Claro que, dependendo do contexto, essa distinção pode ser irrelevante.

**Comment by leoyvens** [comment]
Acho que esse trecho quer dizer que diferentes linguagens tem diferentes conceitos de destrutor, mas em Rust `drop` é a única forma de destrutor. Se diz que a coisa foi "dropped" mesmo que ela não tenha um método `drop`.

**Comment by hsribei** [comment]
Show. Já fiz o `%s/dropar/destruir/` et al.

**Comment by felipewove** [comment]
`To drop` também pode ser `retirar`.

Então no primeiro exemplo "so d was dropped before c" fica "então d foi retirado antes de c"

**Comment by marioidival** [comment]
definido pelo @hsribei como `destruir`.
