### ISSUE TITLE
Como traduzir a palavra crate?

### ISSUE THREAD

**Issue by LorhanSohaky** [rust-br/rust-book-pt-br#67]
Trecho 
> We’ll create a library crate called `gui` that contains the structure of a GUI library. This crate might include some types for people to use, such as `Button` or `TextField`.

**Comment by andre-vm** [comment]
Cara, não vejo a necessidade de traduzir. De qualquer maneira, um rustáceo
iniciante vai precisar usar o site crates.io e também usar a keyword crate.
Então acho que vale a pena deixar em inglês.

**Comment by LorhanSohaky** [comment]
Como deveria traduzir esse trecho? Omito a palavra crate?

**Comment by alexsandro-xpt** [comment]
Palavras importantes visto como palavras relevantes para o negocio como o exemplo de `crate` não podem ser traduzidas no meu ponto de vista..

É igual pegar uma documentação onde o autor tradutor resolveu traduzir `Host` para `Anfitrião` é descer lagrimas dos olhos.

**Comment by LorhanSohaky** [comment]
Então a tradução desse trecho seria:
> Criaremos uma biblioteca crate chamada `gui` que contem a estrutura de uma biblioteca GUI[...]?

**Comment by andre-vm** [comment]
**Library crate** é usado pelo autor para indicar que ele não está se referindo a uma crate binária (uma aplicação executável), mas sim a uma crate que compõe uma biblioteca. Nesse contexto, como ele já diz logo em seguida que se trata de uma biblioteca GUI, talvez podemos traduzir **library crate** apenas como **crate**. Em outros contextos em que isso não fica tão claro, eu traduziria **library crate** como **crate de biblioteca**. Então nesse caso eu deixaria assim:

> Criaremos uma crate chamada `gui` que contém a estrutura de uma biblioteca GUI[...]
