### ISSUE TITLE
README em inglês

### ISSUE THREAD

**Issue by darakeon** [rust-br/rust-book-pt-br#70]
Queria entender porque o README está em inglês.

Sinceramente, eu amo inglês. Prefiro. Meus projetos de github quase todos estão em inglês. Tem um único em português: as histórias que escrevo. Mas, sendo um projeto em português, coloquei também a primeira coisa dele, README, em português. E também os documentos default, como o CONTRIBUTING, poderiam estar em português.

Não sei se a ideia do projeto é ajudar pessoas que não entendem inglês mas, se for, abrir a primeira página e já está tudo em inglês pode afastar a pessoa.

**Comment by marioidival** [comment]
@darakeon não tem ideia. O que acontece que fizemos um fork e não traduzimos o README.

Sinta-se livre para nos ajudar e traduzir :sweat_smile:

**Comment by alexsandro-xpt** [comment]
+1

**Comment by marioidival** [comment]
`help-wanted` @alexsandro-xpt @darakeon <3

**Comment by darakeon** [comment]
@marioidival , consegui arranjar uns minutos pra isso! <3

Não tenho certeza absoluta da tradução de `fold it back in` e `Please see the book as shipped`

**Comment by darakeon** [comment]
@alexsandro-xpt

**Comment by medeirosjoaquim** [comment]
> @marioidival , consegui arranjar uns minutos pra isso! <3
> 
> Não tenho certeza absoluta da tradução de `fold it back in` e `Please see the book as shipped`

Esse trecho foi removido do README porque a edição a qual se referia não está mais disponível.
Então deve remover o trecho que diz:
```
As the second edition of the book will be published by
No Starch, we first iterate here,
then ship the text off to No Starch. 
Then they do editing, and we fold it back in.
```

_"Please see the book as shipped with the latest stable, beta, or nightly Rust releases. "_

Como o livro tem que acompanhar as mudanças na linguagem
 a ideia nessa frase é encarar o livro como lançado junto com:
 a última versão estável, a beta ou o nightly release -- branches do repositório.
Lembrando que bugs, problemas ou novidades sugeridas podem 
já podem ter sido corrigidos na branch master.

Sugestão:

```
You can read the book for free online! Please see the book as shipped with the latest stable, beta, or nightly Rust releases. Be aware that issues in those versions may have been fixed in this repository already.
```

Você pode ler o livro online gratuitamente! Lembre que o livro é lançado junto com as versões: estável, beta e nightly dos repositórios da linguagem. Então saiba que problemas que podem existir nessas versões podem já ter sido corrigidos na branch master, que é atualizada com mais frequência.

**Comment by glaucia86** [comment]
Olá! Vocês estão precisando de ajuda para tradução de documentação? Se sim, me avisem que posso ajudar também. Assim como já venho ajudando nos projetos do React Community & Nodejs Foundation. (@glaucia86)

**Comment by darakeon** [comment]
@glaucia86 , se quiser fazer commits em cima do [PR](https://github.com/rust-br/rust-book-pt-br/pull/71) que foi aberto... Tô meio out no momento...

**Comment by victorteodoro** [comment]
## PR aberto
Mandei um pr ontem pra continuar os trabalhos: https://github.com/rust-br/rust-book-pt-br/pull/72
