### ISSUE TITLE
Tradução do Capítulo 8-0 Fundamental Collections

### ISSUE THREAD

**Issue by everton3x** [rust-br/rust-book-pt-br#91]
Vou fazer a tradução do Capítulo 8-0 Fundamental Collections (em second edition é nomeado de Common Collections).

**Comment by adjoli** [comment]
Olá @everton3x, você ainda está trabalhando nesta tradução?

**Comment by everton3x** [comment]
Olá @adjoli.
Não e nem comecei. Abortei o Rust.
